### ISSUE TITLE
Magisk Hide (LygiskHide) support

### ISSUE THREAD

**Issue by firefinchdev** [programminghoch10/Lygisk#1]
As far as I am aware, Magisk will be removing Magisk Hide support (because of politics?)
Will Lygisk still support and maintain MagiskHide when official Magisk hide is removed?

Although hardware based detections may not work, but most of the apps work if we simply just hide root from app (using Magisk Manager).

**Comment by programminghoch10** [comment]
No, we will not support MagiskHide further than Magisk does it, as this was not the reason why we forked in the first place.
I do know MagiskHide is something people would like to see continued in a fork, but we are not capable to support or maintain MagiskHide.
Please remember though, just because MagiskHide is dead does not mean it won't exist anymore. It will definively be replaced by a module. And you can always continue to use Magisk v23 if you like to.
Just wait for how Magisk and the planned module continue here.

**Comment by firefinchdev** [comment]
Okay, thanks for the info...
Hoping that all of us can continue using our favourite apps along with root...
