### ISSUE TITLE
Problems with Lygisk Manager v25.100

### ISSUE THREAD

**Issue by heinhuiz** [programminghoch10/Lygisk#11]
Situation:
Currently on Lygisk v24.300
Manager indicates an update for the app to v25.100, which installs flawlessly.
New version of the Manager indicates an update for Lygisk, which does not install and exits with a failure code: 1.

Sideloading v25.100 works though, but then the Manager disappears.
Trying to install the Manager manually from the APK seems to work, but the app does not open and has disappeared from the system.
Device is still rooted though.

The only way for me to recover was sideloading Magisk v25.100, installing the Magisk Manager, and from there I could restore the boot image and delete the Magisk Manager app.

Installing v25.100 through sideload with the original boot image also results in a disappearing Manager app. I uninstalled Lygisk again with the method above. Now I'm back on v24.300 and the app is staying.

**Comment by Iey4iej3** [comment]
Second this.

**Comment by icedream** [comment]
This problem is most likely caused by the APK signature check routine that was added in Magisk v25. That check even fails on the official Magisk app on my Galaxy S8 (on Ivan Meler's LineageOS 19.1 ROM) and it will generate log entries in logcat hinting such.

The debug build there does not have the issue.
