### ISSUE TITLE
Magisk module repository

### ISSUE THREAD

**Issue by 1RandomDev** [programminghoch10/Lygisk#2]
Apparently in the Lygisk app it's not possible to install modules directly from the official magisk repository. However manual installation works just fine

**Comment by nillebor** [comment]
thats alright. John Wu alias [topjohnwu](https://github.com/topjohnwu) has stopped supporting online addons. The same goes for magisk hinde. So that's not the problem with the git here, BUT the reslease is wrong!

One thinks the pepached version is the release, but actually installs a canary to be recognized by the version 23.015 and not release v23.0!

the rest works, maybe the release should be renamed

**Comment by 1RandomDev** [comment]
Ok didn't know that. Does that also mean I will have to check for updates manually or can packages still provide their own update url?

**Comment by nillebor** [comment]
as far as I have read it is about the provision of the add-ons in magisk. look in the xda thread or test it!

**Comment by programminghoch10** [comment]
we will not implement any other module repository, this is not the reason of this mod.
you gotta look how magisk solves this, lygisk will follow it.
