### ISSUE TITLE
Lygisk 26404

### ISSUE THREAD

**Issue by dissidius** [programminghoch10/Lygisk#34]
Hello!

Canary and Madness still point to dated versions of Lygisk/Magisk.

Can you bump Canary to 26404 or at least Madness?

I cannot seem to be able to updeate Shamiko, as the latest version in Lygysk Madness is 26402 and Shamiko requires 26404 or newer.

Not an issue of course but i didn't know how to ask/request.

Cheers and thanks for the awesome work 🥂🥂

**Comment by programminghoch10** [comment]
Our build system doesn't allow for beta, canary and madness to be updated seperately.
This is because the build system automatically merges our changes to stable upon the given newer versions.
As soon as some breaking change prevents this from happening this process will halt and will only continue when stable is updated.
You will have to wait for a stable update, or merge it yourself.
